[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
comadre = "CMDRxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.devnet]
comadre = "CMDRxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/tanda.spec.ts' --exit"
